### ISSUE TITLE
examples_cant run

### ISSUE THREAD

**Issue by ge53** [wouterverweirder/kinect2#43]
i am trying to run kinect2 examples--using Windows 10, loaded the Kinect v2 SDK and node(v6.9.5) --(basic "usage" runs ok, these issues are in browser)getting this error:
thanks..
   <i> _Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Windows\System32\node_modules\kinect2\examples\depth-feed-browser\index.js:2:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm WARN depth-feed-browser@0.0.30 No repository field.
C:\Windows\System32\node_modules\kinect2\examples\depth-feed-browser>_</i>

**Comment by ge53** [comment]
ran 'npm install'--worked!
thanks for this great lib
